apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes-backend
  template:
    metadata:
      labels:
        app: notes-backend
    spec:
      containers:
      - name: notes-backend
        image: gszpura/notes_backend:0.1
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_HOST
          value: postgres-service
---
apiVersion: v1
kind: Service
metadata:
  name: notes-backend-service
spec:
  selector:
    app: notes-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
